#!/bin/bash
# Quick reference for golang refactor collaboration

echo "=== OpenCode Golang Refactor - Agent Workflow ==="
echo ""
echo "AGENT 1 (golang-refactor) - TUI & Backend"
echo "  Branch: golang-refactor"
echo "  Focus: TUI, backend services, API"
echo "  Commands:"
echo "    > git checkout golang-refactor"
echo "    > go test -v ./... && make build"
echo "    > git fetch origin golang-refactor-v2"
echo ""
echo "AGENT 2 (golang-refactor-v2) - Design, Perf, GUI"
echo "  Branch: golang-refactor-v2"
echo "  Focus: Architecture validation, performance optimization, documentation"
echo "  Commands:"
echo "    > git checkout golang-refactor-v2"
echo "    > git fetch origin golang-refactor"
echo "    > git log origin/golang-refactor...HEAD"
echo ""
echo "SHARED PACKAGES (controlled by Agent 1):"
echo "  - /go/pkg/types/      (type definitions)"
echo "  - /go/pkg/core/       (file & project services)"
echo "  - /go/pkg/api/        (HTTP handlers & client)"
echo ""
echo "STATUS (Feb 8, 2026):"
echo "  ✅ Scaffold complete"
echo "  ✅ Backend services (4/4 tests passing)"
echo "  ✅ TUI skeleton + 4 core tests"
echo "  🔄 Phase 2: Enhance TUI features"
echo ""
echo "Next Steps:"
echo "  Agent 1: Add syntax highlighting, rich editing, file watching"
echo "  Agent 2: Architecture review, performance benchmarks"
echo ""
echo "See /go/COLLABORATION.md for full details"
